<a href="https://colab.research.google.com/github/19PA1A0237/AI-lab/blob/master/Experiment-1%20%3A%20Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Experiment 1

## 1) Different ways to create Numpy arrays.

In [ ]:
import numpy as np
a = np.array([4,8,9])
print(a)

[4 8 9]


In [10]:
s = np.array([[7,3,4],[9,2,6]])
print(s)

[[7 3 4]
 [9 2 6]]


## 2) Add,remove,modify elements in an array.

In [ ]:
b = np.append(a,[6,5,8])
print(b)

[4 8 9 6 5 8]


In [ ]:
q = np.delete(a,2)
print(q)

[4 8]


In [ ]:
b = np.array([6,4,3,1,9,5])
b[b<2]=-1
print(b)

[ 6  4  3 -1  9  5]


## 3)Arthematic operations on Numpy array.

In [ ]:
import numpy as np
b = np.array([[1,2],[4,5]])
c = np.array([[6,7],[7,9]])
print(np.add(b,c))
print(np.subtract(b,c))
print(np.multiply(b,c))
print (np.divide(b,c))

[[ 7  9]
 [11 14]]
[[-5 -5]
 [-3 -4]]
[[ 6 14]
 [28 45]]
[[0.16666667 0.28571429]
 [0.57142857 0.55555556]]


# 4)Slicing and iterating of numpy arrays.

### slicing

In [ ]:
import numpy as np
arr = np.array([7,5,3,9,2,5])
print(arr[2:5])

[3 9 2]


### iterating

In [ ]:
for x in arr:
  print(x)

7
5
3
9
2
5


## 5)Matrix operation on numpy arrays.

In [ ]:
import numpy as np
d = np.array([[4,3],[2,1]])
v = np.array([[8,7],[6,5]])
print(np.add(d,v))
print(np.subtract(d,v))    
print(np.divide(d,v))

[[12 10]
 [ 8  6]]
[[-4 -4]
 [-4 -4]]
[[0.5        0.42857143]
 [0.33333333 0.2       ]]
